# Enable CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            enabled: true

    csrf_protection:
        stateless_token_ids:
            - authenticate
            - logout
